name: HumanNPC
version: 0.1.0
author: BeeAZ
src-namespace-prefix: beeaz\humannpc
main: beeaz\humannpc\HumanNPC
api: 5.0.0

commands:
  humannpc:
    description: HumanNPC command
    permission: humannpc.command.humannpc
    aliases: [hnpc, npc]
  runcommandas:
    description: Run command as
    permission: humannpc.command.rca
    aliases: [rca]

permissions:
  humannpc.command.humannpc:
    default: op
  humannpc.command.rca:
    default: op
