name: HumanNPC
version: 0.0.6

src-namespace-prefix: BeeAZ\HumanNPC
main: BeeAZ\HumanNPC\Loader
api: 5.0.0

author: BeeAZ

commands:
  hnpc:
    description: HumanNPC Commands
    permission: humannpc.command
  rca:
    description: Rca Commands
    permission: humannpc.rca
permissions:
  humannpc.command:
    default: op
  humannpc.rca:
    default: op
