name: HumanNPC
version: 0.1.0

src-namespace-prefix: HumanNPC
main: HumanNPC\Loader
api: 5.0.0

author: BeeAZ & me

commands:
  hnpc:
    description: HumanNPC Commands
    permission: humannpc.command
  rca:
    description: Rca Commands
    permission: humannpc.rca
permissions:
  humannpc.command:
    default: op
  humannpc.rca:
    default: op