name: HumanNPC
version: 0.0.2
main: BeeAZ\HumanNPC\Loader
author: BeeAZ
api: 5.0.0

commands:
  hnpc:
   description: HumanNPC Commands
   permission: humannpc.command
  rca:
   description: Rca Commands
   permission: humannpc.rca
permissions:
  humannpc.command:
   default: op
  humannpc.rca:
   default: op
